apiVersion: v1
kind: Service
metadata:
  name: sonalysis-web-service
  labels:
    app: sonalysis-web
spec:
  selector:
    app: sonalysis-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonalysis-web
  namespace: default
  labels:
    app: sonalysis-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonalysis-web
  template:
    metadata:
      labels:
        app: sonalysis-web
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sonalysis-service"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "3005"
        #dapr.io/config: "serverconfig"
        
    spec:
      containers:
      - name: sonalysis-web
        image: parallelscore/sonalysis_web:latest
        ports:
        - containerPort: 3005      
        imagePullPolicy: IfNotPresent
        # added below lines to test crashing error

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: default
  labels:
    app: sonalysis-web
    deploymentName: sonalysis-web
spec:
  scaleTargetRef:
    name: sonalysis-web
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod:  15 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
