name: Sonalysis-deployment

on:
   push:
      branches: [ ]

jobs:
   deploy:
      name: Deploy 
      runs-on: ubuntu-latest
      steps:
      - name: ssh deployment
        uses: appleboy/ssh-action@master
        with:
           host: ${{secrets.SSH_HOST_ENV}}
           username: ${{secrets.SSH_USERNAME}}
           key: ${{secrets.SSH_KEY_ENV}}
           port: ${{secrets.SSH_PORT}}
           script: |
              cd /var/www/microservices/
              cd sonalysis/
              git pull origin main
              git status
              source ~/.nvm/nvm.sh;
              npm install;
              pm2 restart 5;
              systemctl restart nginx

